#13: Implemented checkpoints after every epoch for the deepfake detector.
BasicallyOk/deepfake-lip-sync pull request #23
Opened 2022-12-04 21:28 UTC by HueyAmiNhvtim

## [What does this PR do?](https://google.github.io/eng-practices/review/developer/cl-descriptions)

This PR implemented checkpoints after every epoch during training so that if something bad happens, it can continue using the checkpoint from the last successful epoch. Also implemented restoration from old_models too, tho that one is
incomplete, and should be resolved later on.

## [Github Issue Number](https://docs.github.com/en/issues/tracking-your-work-with-issues/about-issues)

Resolves:

Relates to:
Nothing

## Author checklist
If any of these points have yet to be satisfied, make sure that you set the title to the format DRAFT #issue-num Title

- [ ] The title is short and descriptive of the PR. Must start with the Github Issue Number (format: #issue-num Title).
- [ ] The description follows proper cl description practices and mentions related Github Issues (make sure this is the first thing you mention).
- [ ] Branch has merged in the **latest version of main**
- [ ] **Linting** has occured, as per the project linting config 
- [ ] All changed functions have proper **docstring** to describe what they do and how to use them.
 
 
## Reviewer checklist
Second reviewer will need to double check all of these points

- [ ] Relevant issue is mentioned in description 
- [ ] Code solves the issue
- [ ] Code is the best solution for the issue
- [ ] Branch is **ahead of main**
- [ ] Ensures the fix/feature works locally

2022-12-11 15:11 UTC, BasicallyOk requested changes

2022-12-11 15:11 UTC, BasicallyOk commented on models/visual_quality_discriminator.py
> +def load_or_create_new_model():
Bad idea, in a GAN setup, we do not want a premade model at all.
For the Synch Accuracy one we will implement that separately.

2022-12-11 15:11 UTC, BasicallyOk commented on models/visual_quality_discriminator.py
> +train()
Put this in a if __name__ == "__main__": block.
We want this file to export the model, not train it

2022-12-11 15:16 UTC, BasicallyOk commented on models/visual_quality_discriminator.py
> +def load_or_create_new_model():
To resolve this, make sure that:

- Call the function load_model(), we won't need polymorphism, but it's good practice to be consistent and concise.
- If you want to load model, or train, do that in the main block. This file's main purpose is to define the model, the training and testing *must* be done only in a main block.

2022-12-11 15:21 UTC, BasicallyOk commented
Make sure that all changes are mentioned in the description.
Only the checkpoint change was mentioned.

2022-12-19 09:02 UTC, HueyAmiNhvtim commented on models/visual_quality_discriminator.py
> +def load_or_create_new_model():
So should we remove that model.save line in the visual quality discriminator model? Because the visual quality discriminator is not part of the GAN setup (as in not being trained alongside the sync_accuracy and the generator one) if I remember correctly.

2022-12-19 09:03 UTC, HueyAmiNhvtim commented on models/visual_quality_discriminator.py
> +train()
I suppose that I should also put the check point stuff not in the functions and the code for testing the model in that block then.

2022-12-26 12:18 UTC, BasicallyOk commented on models/visual_quality_discriminator.py
> +def load_or_create_new_model():
Yes, it's still better to have consistent and predictable function design.

We'll just train and save it separately

2022-12-26 12:20 UTC, BasicallyOk commented on models/visual_quality_discriminator.py
> +train()
Yes, but which part of the checkpoints do you mean. We still wamt to have proper checkpoints implemented to avoid having to restart when anything happens

2024-04-28 23:21 UTC, closed without merging